config/routes.rb
CornellRadio::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :page_contents, only: [:update, :edit]
  resources :show_users, only: [:new, :create, :destroy]
  resources :shows
  resources :podcasts
  resources :audio, :only => :new
  resources :posts
  resources :users

  root 'static_pages#home'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/schedule', to: 'static_pages#schedule', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/win', to: 'static_pages#win', via: 'get'
  match '/events', to: 'static_pages#events', via: 'get'
  match '/get_involved', to: 'static_pages#get_involved', via: 'get'
  match '/sports', to: 'static_pages#sports', via: 'get'
  match '/connect', to: 'static_pages#connect', via: 'get'
  match '/userposts/:id', to: 'static_pages#userposts', via: 'get'
  match '/showposts/:id', to: 'static_pages#showposts', via: 'get'
  match '/admin', to: 'sessions#new', via: 'get'
  match '/subscribe', to: 'mailchimp#subscribe', via: 'post'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/show_user.rb
# == Schema Information
#
# Table name: show_users
#
#  id         :integer          not null, primary key
#  user_id    :string(255)
#  show_id    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class ShowUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
  validates :show_id, presence: true
  validates :user_id, presence: true
end

app/controllers/show_users_controller.rb
class ShowUsersController < ApplicationController
  before_action :set_show_user, only: [:show, :edit, :update, :destroy]

  # GET /show_users
  # GET /show_users.json
  def index
    @show_users = ShowUser.all
  end

  # GET /show_users/1
  # GET /show_users/1.json
  def show
  end

  # GET /show_users/new
  def new
    @show_user = ShowUser.new()
  end

  # GET /show_users/1/edit
  def edit
  end

  # POST /show_users
  # POST /show_users.json
  def create
    @show_user = ShowUser.new(show_user_params)

    respond_to do |format|
      if @show_user.save
        format.html { redirect_to @show_user, notice: 'Show user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @show_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @show_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /show_users/1
  # PATCH/PUT /show_users/1.json
  def update
    respond_to do |format|
      if @show_user.update(show_user_params)
        format.html { redirect_to @show_user, notice: 'Show user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @show_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /show_users/1
  # DELETE /show_users/1.json
  def destroy
    @show_user.destroy
    respond_to do |format|
      format.html { redirect_to show_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show_user
      @show_user = ShowUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_user_params
      params.require(:show_user).permit(:user_id, :show_id)
    end
end

app/helpers/show_users_helper.rb
module ShowUsersHelper
end

app/views/show_users/_form.html.erb
<%= form_for(@show_user) do |f| %>
  <% if @show_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show_user.errors.count, "error") %> prohibited this show_user from being saved:</h2>

      <ul>
      <% @show_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :show_id %><br>
    <%= f.text_field :show_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/show_users/edit.html.erb
<h1>Editing show_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @show_user %> |
<%= link_to 'Back', show_users_path %>

app/views/show_users/index.html.erb
<h1>Listing show_users</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Showid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @show_users.each do |show_user| %>
      <tr>
        <td><%= show_user.user_id %></td>
        <td><%= show_user.show_id %></td>
        <td><%= link_to 'Show', show_user %></td>
        <td><%= link_to 'Edit', edit_show_user_path(show_user) %></td>
        <td><%= link_to 'Destroy', show_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show user', new_show_user_path %>

app/views/show_users/new.html.erb
<h1>New show_user</h1>

<%= render 'form' %>

<%= link_to 'Back', show_users_path %>

app/views/show_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @show_user.user_id %>
</p>

<p>
  <strong>Showid:</strong>
  <%= @show_user.show_id %>
</p>

<%= link_to 'Edit', edit_show_user_path(@show_user) %> |
<%= link_to 'Back', show_users_path %>