config/routes.rb
CornellRadio::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :page_contents, only: [:update, :edit]
  resources :show_users, only: [:new, :create, :destroy]
  resources :shows
  resources :podcasts
  resources :audio, :only => :new
  resources :posts
  resources :users

  root 'static_pages#home'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/schedule', to: 'static_pages#schedule', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/win', to: 'static_pages#win', via: 'get'
  match '/events', to: 'static_pages#events', via: 'get'
  match '/get_involved', to: 'static_pages#get_involved', via: 'get'
  match '/sports', to: 'static_pages#sports', via: 'get'
  match '/connect', to: 'static_pages#connect', via: 'get'
  match '/userposts/:id', to: 'static_pages#userposts', via: 'get'
  match '/showposts/:id', to: 'static_pages#showposts', via: 'get'
  match '/admin', to: 'sessions#new', via: 'get'
  match '/subscribe', to: 'mailchimp#subscribe', via: 'post'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/podcast.rb
# == Schema Information
#
# Table name: podcasts
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  show_id     :integer
#  title       :string(255)
#  audio       :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Podcast < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  # validates :audio, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 250 }
  mount_uploader :audio, AudioUploader
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
    @podcast.update_attribute :key, params[:key]
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    if @podcast.save
      Resque.enqueue(AudioProcessor, @podcast.id, @podcast.key)
      # podcast = Podcast.find(@podcast.id)
      # podcast.key = params['podcast']['new_key']
      # podcast.remote_audio_url = podcast.audio.direct_fog_url(:with_path => true)
      # podcast.save!
      
      flash[:success] = "Podcast successfully created! Processing audio"
      redirect_to podcasts_path
    else
      redirect_to new_podcast_path
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:user_id, :show_id, :title, :audio, :description, :key)
    end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_podcast.html.erb
<% @id = podcast.id %>
<script type="text/javascript">
  $(document).ready(function() {
    var myCirclePlayer = new CirclePlayer("#jquery_jplayer_<%= @id %>",
      {
          mp3: "<%= podcast.audio.url %>"
      }, {
          cssSelectorAncestor: "#cp_container_<%= @id %>",
          swfPath: "http://www.jplayer.org/latest/js/Jplayer.swf",
          wmode: "window",
          kepEnabled: true,
          supplied: "mp3",
          solution: "html, flash"
      }
    );
  });
</script>
<li style="height:120px;">
  <div id="jquery_jplayer_<%= @id %>" class="cp-jplayer"></div>
  <div id="cp_container_<%= @id %>" class="cp-container">
      <div class="cp-buffer-holder">
          <div class="cp-buffer-1"></div>
          <div class="cp-buffer-2"></div>
      </div>
      <div class="cp-progress-holder">
          <div class="cp-progress-1"></div>
          <div class="cp-progress-2"></div>
      </div>
      <div class="cp-circle-control"></div>
      <ul class="cp-controls">
          <li><a href="#" class="cp-play" tabindex="1">play</a></li>
          <li><a href="#" class="cp-pause" style="display:none;" tabindex="1">pause</a></li>
      </ul>
  </div>
  <%= link_to(podcast) do %>
    <span class="title"><%= podcast.title %>
      <% unless podcast.user.nil? %>
         - <%= podcast.user.first_name %> <%= podcast.user.last_name %>
      <% end %>
    </span>
    <% if !podcast.description.nil? %>
      <span class="content"><%= podcast.description[0,160] %></span>
    <% end %>
    <span class="timestamp">
      Posted <%= time_ago_in_words(podcast.created_at) %> ago.
    </span>
  <% end %>
</li>

app/views/podcasts/edit.html.erb
<div class="box formBox">
  <h1>New Post</h1>
  <%= form_for @podcast do |f| %>

    <%= render '/shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Max 250 char"%>
    <br><br>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/podcasts/index.html.erb
<% provide :title, "Podcasts from CornellRadio.com" %>
<div class="box sideBox">
  <%= render 'shared/on_now' %>
</div>
<div class="box feedBox">
  <h1>Podcasts</h1>
  <ol class="posts">
    <%= render @podcasts %>
  </ol>
</div>

app/views/podcasts/new.html.erb
<div class="box formBox">
  <h1>New Podcast</h1>
  <%= form_for @podcast do |f| %>

    <%= render '/shared/error_messages', object: f.object %>

    <% #link_to "Upload audio clip", new_audio_path, class:'btn' %>

    <% if current_user.level.to_i < 2 %>
      <%= f.label :user_id %>
      <%= f.select :user_id, User.all.collect { |user| ["#{user.first_name} #{user.last_name}", user.id] } %>
    <% else %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>

    <%= f.label :show_id %>
    <% if current_user.level.to_i < 2 %>
      <%= f.select :show_id, Show.all.collect { |show| [ show.title, show.id]}, { include_blank: true }  %>
    <% else %>
      <%= f.select :show_id, current_user.shows.collect { |show| [ show.title, show.id]}, { include_blank: true }  %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Max 250 char"%>

    <%= f.hidden_field :key %>
    <br><br>
    <%= f.submit value:"Upload Podcast", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/podcasts/show.html.erb
<% provide :title, @podcast.title %>
<% @id = @podcast.id %>
<script type="text/javascript">
  $(document).ready(function(){
    $("#jquery_jplayer_<%= @id %>").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          title: "<%= @podcast.title %>",
          mp3: "<%= @podcast.audio_url %>",
        });
      },
      cssSelectorAncestor: "#jp_container_<%= @id %>",
      swfPath: "/js",
      supplied: "mp3"
    });
  });
</script>
<div class="box sideBox">
  <%= render 'shared/on_now' %>
  <ol class="sideList">
    <li><%= link_to "View all posts", posts_path %></li>
    <% unless @podcast.user.nil? %>
      <li><%= link_to "View other posts by #{@podcast.user.first_name}", "/userposts/#{@podcast.user.id}" %></li>
    <% end %>
    <% if @podcast.show %>
      <li><%= link_to "View other posts from #{@podcast.show.title}", "/showposts/#{@podcast.show.id}" %></li>
    <% end %>
  </ol>
</div>
<div class="box feedBox">
  <h2><%= @podcast.title %></h2>
  <% unless @podcast.user.nil? %>
    <h3>by <%= link_to @podcast.user.first_name, @podcast.user %></h3>
  <% end %>
  <% if @podcast.show %>
    <h4>from <%= link_to @podcast.show.title, @podcast.show %></h4>
  <% end %>
  <% if current_user == @podcast.user || (signed_in? && current_user.level.to_i < 2) %>
    <h4><%= link_to "edit", edit_podcast_path(@podcast) %> | <%= link_to "delete", @podcast, method: :delete, data: { confirm: "You sure?" }, title: @podcast.description %></h4>
  <% end %>
  <p><%= @podcast.description %></p>
  <div id="jquery_jplayer_<%= @id %>" class="jp-jplayer"></div>
  <div id="jp_container_<%= @id %>" class="jp-audio">
    <div class="jp-type-single">
      <div class="jp-gui jp-interface">
        <ul class="jp-controls">
          <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
          <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
          <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
          <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
          <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
          <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
        </ul>
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
        <div class="jp-time-holder">
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
          <ul class="jp-toggles">
            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
          </ul>
        </div>
      </div>
      <div class="jp-details">
        <ul>
          <li><span class="jp-title"></span></li>
        </ul>
      </div>
      <div class="jp-no-solution">
        <span>Update Required</span>
        To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
      </div>
    </div>
  </div> 
</div>