config/routes.rb
CornellRadio::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :page_contents, only: [:update, :edit]
  resources :show_users, only: [:new, :create, :destroy]
  resources :shows
  resources :podcasts
  resources :audio, :only => :new
  resources :posts
  resources :users

  root 'static_pages#home'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/schedule', to: 'static_pages#schedule', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/win', to: 'static_pages#win', via: 'get'
  match '/events', to: 'static_pages#events', via: 'get'
  match '/get_involved', to: 'static_pages#get_involved', via: 'get'
  match '/sports', to: 'static_pages#sports', via: 'get'
  match '/connect', to: 'static_pages#connect', via: 'get'
  match '/userposts/:id', to: 'static_pages#userposts', via: 'get'
  match '/showposts/:id', to: 'static_pages#showposts', via: 'get'
  match '/admin', to: 'sessions#new', via: 'get'
  match '/subscribe', to: 'mailchimp#subscribe', via: 'post'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/page_content.rb
# == Schema Information
#
# Table name: page_contents
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class PageContent < ActiveRecord::Base
end

app/controllers/page_contents_controller.rb
class PageContentsController < ApplicationController
  before_action :set_page_content, only: [:show, :edit, :update, :destroy]

  # GET /page_contents
  # GET /page_contents.json
  def index
    @page_contents = PageContent.all
  end

  # GET /page_contents/1
  # GET /page_contents/1.json
  def show
  end

  # GET /page_contents/new
  def new
    @page_content = PageContent.new
  end

  # GET /page_contents/1/edit
  def edit
  end

  # POST /page_contents
  # POST /page_contents.json
  def create
    @page_content = PageContent.new(page_content_params)

    respond_to do |format|
      if @page_content.save
        format.html { redirect_to @page_content, notice: 'Page content was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @page_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_contents/1
  # PATCH/PUT /page_contents/1.json
  def update
    respond_to do |format|
      if @page_content.update(page_content_params)
        format.html { redirect_to @page_content, notice: 'Page content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_contents/1
  # DELETE /page_contents/1.json
  def destroy
    @page_content.destroy
    respond_to do |format|
      format.html { redirect_to page_contents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_content
      @page_content = PageContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_content_params
      params.require(:page_content).permit(:title, :content)
    end
end

app/helpers/page_contents_helper.rb
module PageContentsHelper
end

app/views/page_contents/_form.html.erb
<%= form_for(@page_content) do |f| %>
  <% if @page_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_content.errors.count, "error") %> prohibited this page_content from being saved:</h2>

      <ul>
      <% @page_content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/page_contents/edit.html.erb
<h1>Editing page_content</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_content %> |
<%= link_to 'Back', page_contents_path %>

app/views/page_contents/index.html.erb
<h1>Listing page_contents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @page_contents.each do |page_content| %>
      <tr>
        <td><%= page_content.title %></td>
        <td><%= page_content.content %></td>
        <td><%= link_to 'Show', page_content %></td>
        <td><%= link_to 'Edit', edit_page_content_path(page_content) %></td>
        <td><%= link_to 'Destroy', page_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page content', new_page_content_path %>

app/views/page_contents/new.html.erb
<h1>New page_content</h1>

<%= render 'form' %>

<%= link_to 'Back', page_contents_path %>

app/views/page_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page_content.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page_content.content %>
</p>

<%= link_to 'Edit', edit_page_content_path(@page_content) %> |
<%= link_to 'Back', page_contents_path %>