config/routes.rb
CornellRadio::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :page_contents, only: [:update, :edit]
  resources :show_users, only: [:new, :create, :destroy]
  resources :shows
  resources :podcasts
  resources :audio, :only => :new
  resources :posts
  resources :users

  root 'static_pages#home'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/schedule', to: 'static_pages#schedule', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/win', to: 'static_pages#win', via: 'get'
  match '/events', to: 'static_pages#events', via: 'get'
  match '/get_involved', to: 'static_pages#get_involved', via: 'get'
  match '/sports', to: 'static_pages#sports', via: 'get'
  match '/connect', to: 'static_pages#connect', via: 'get'
  match '/userposts/:id', to: 'static_pages#userposts', via: 'get'
  match '/showposts/:id', to: 'static_pages#showposts', via: 'get'
  match '/admin', to: 'sessions#new', via: 'get'
  match '/subscribe', to: 'mailchimp#subscribe', via: 'post'

  mount Ckeditor::Engine => '/ckeditor'

end

app/views/layouts/_header.html.erb
<% if signed_in? %>
  <span class="options">
    <ol>
      <li><%= link_to "Your page", current_user %></li>
      <li><%= link_to "Add post", new_post_path %></li>
      <li><%= link_to "Add podcast", new_audio_path %></li>
      <% current_user.shows.each do |show| %>
        <li><%= link_to show.title, show %></li>
      <% end %>
      <% if current_user.level.to_i < 2 %>
        <li><%= link_to "Add new user", new_user_path %></li>
        <li><%= link_to "Add new show", new_show_path %></li>
      <% end %>
      <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    </ol>
  </span>
<% end %>
<div>
  <span id="listen">
    <a id="play" href="#" onclick="window.open('http://apps.streamlicensing.com/player-popup.php?sid=2660&stream_id=4543','player','width=405,height=373,scrollbars=no');javascript:history.go(-1);return false;">
      <%= image_tag("listenlive.png", width: "200") %>
    </a>
    <div class="listen-alts">
      <a href="http://tunein.com/radio/CornellRadiocom-s225743/">
        Check us out on TuneIn!
      </a>
      <div>
        Listening on mobile? <a href="http://server.nobexrc.com/sl.aspx?id=2660">Download our app</a>
      </div>
    </div>
  </span>
  <div id="logo">
    <%= image_tag("CR_Header_stroke.png", width: "200") %>
    <%= image_tag("CR_transparent5_dark.png", width: "45") %>
  </div>
  <audio id="audio">
    <source  src="http://www.live365.com/play/371252">
  </audio>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              On-Air <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Schedule", schedule_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Shows", shows_path %></li>
              <li><%= link_to "Personalities", users_path %></li>
            </ul>
          </li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              The Feeds <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Everything", media_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Just Posts", posts_path %></li>
              <li><%= link_to "Just Podcasts", podcasts_path %></li>
            </ul>
          </li>
          <li><%= link_to "Get Involved", get_involved_path %></li>
          <li><%= link_to "Big Red Sports", sports_path %></li>
          <li><%= link_to "Connect", connect_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script> // Google analytics code
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-60066770-1', 'auto');
    ga('send', 'pageview');

  </script>
  <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
  </script>

</head>
<body>
  <div class="container">
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= render 'layouts/nav' %>
    <% flash.each do |key,value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
<footer>
  <% if params[:action] == 'home' %>
    <a class="pull-right" href="http://www.streamlicensing.com/directory/?action=verify&sid=2660" target="_Blank">
      <img src="http://www.streamlicensing.com/directory/images/streamlicensing-badge.png" border="0">
    </a>
  <% end %>
</footer>
</html>

app/views/layouts/bare.html.erb
<html>
<head> 
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>
<body>
  <%= yield %>
</body>
</html>